export const fallbackExcuses = {
  work: {
    friendly: [
      "I'm so sorry, but my manager just called an emergency meeting that I can't miss. Rain check?",
      "My client moved up their deadline and I need to finish this project tonight. I feel terrible about this!",
      "I just got a call that our server went down and I'm the only one who can fix it. This never happens!",
      "My colleague is sick and I have to cover their presentation first thing tomorrow morning.",
      "I completely forgot I promised to help my coworker with a crucial report that's due tonight.",
      "My boss just assigned me an urgent task that needs to be done before tomorrow's board meeting.",
      "I have to stay late to prep for a surprise audit tomorrow - my department head just told us.",
      "A major client is having issues and they specifically requested me to handle the call tonight.",
      "I just remembered I have a mandatory training session early tomorrow that I can't reschedule.",
      "My work laptop crashed and I need to reinstall everything before my morning presentation.",
      "I have to finish reviewing contracts that legal needs first thing in the morning.",
      "My team lead asked me to prepare an emergency backup plan for tomorrow's product launch.",
      "I just got notified that I have to attend a last-minute video conference with our overseas partners.",
      "My supervisor needs me to compile quarterly reports that are due at 9 AM sharp tomorrow.",
      "I have to stay and help train the new intern who starts tomorrow morning.",
      "Our biggest client just requested changes to their project and I'm the lead on it.",
      "I need to finish debugging code before our system maintenance window tonight.",
      "My department is short-staffed and I volunteered to cover the evening shift.",
      "I have to prepare talking points for my manager's presentation to the executives tomorrow.",
      "I just learned I need to attend a compliance meeting first thing in the morning.",
      "My work computer got a virus and IT needs me to stay to get it fixed properly.",
      "I have to finish entering data for the monthly report that goes out tomorrow.",
      "My supervisor asked me to review and approve timesheets before payroll processes tonight.",
      "I need to prepare materials for a workshop I'm facilitating tomorrow morning.",
      "Our office internet went down and I need to hotspot to finish uploading important files."
    ],
    urgent: [
      "EMERGENCY at work - server crash and I'm the only one who can fix it. Have to go NOW!",
      "Boss just called - major client crisis and I need to be there immediately!",
      "Code red at the office - security breach and they need me there right now!",
      "My project deadline just moved up to 6 AM tomorrow - I have to work all night!",
      "Urgent: My coworker had a family emergency and I need to cover their shift immediately!",
      "CRISIS: Our main system is down and customers are calling - I have to go fix it!",
      "Emergency board meeting called and I need to prepare materials RIGHT NOW!",
      "Major data loss at work - I'm the backup specialist and need to restore everything tonight!",
      "Client threatening to sue - legal needs me there immediately for damage control!",
      "System failure during our biggest sale day - I have to get there and fix it now!",
      "Fire drill went wrong - actual emergency and they need all department heads there!",
      "Our website was hacked - I'm head of security and need to respond immediately!",
      "Urgent: Payroll system crashed on payday - employees are panicking and I have to fix it!",
      "Major equipment malfunction - production stopped and I'm the only tech who can repair it!",
      "Emergency audit started early - compliance needs me there with all records NOW!",
      "Power outage at main office - I need to coordinate backup systems immediately!",
      "Client's wedding is tomorrow and their entire order was corrupted - I have to remake everything!",
      "News crew is coming to film our office in an hour - boss needs me there for prep!",
      "Urgent vendor meeting - they're threatening to terminate our contract and I have to negotiate!",
      "Emergency evacuation drill became real emergency - I'm a floor warden and must respond!",
      "Database corruption wiped out months of work - I need to attempt recovery immediately!",
      "Urgent: International client calling in 20 minutes and I'm the only one who speaks their language!",
      "Major software bug is crashing customer orders - I have to patch it before we lose more money!",
      "Office flooding from burst pipe - I need to save computer equipment and files right now!",
      "Urgent deadline moved up - presentation to investors is now at 7 AM instead of next week!"
    ],
    subtle: [
      "I have some work stuff I should probably catch up on tonight, if that's okay with you.",
      "My laptop's been acting up and I should probably back up my files before tomorrow.",
      "I have this early meeting tomorrow and should probably review my notes once more.",
      "I'm feeling a bit behind on a project and could use the evening to make some progress.",
      "I promised myself I'd organize my work files tonight - it's been on my to-do list forever.",
      "I have this report due soon and should probably give it another look tonight.",
      "My work schedule is pretty packed tomorrow, so I should prep a few things tonight.",
      "I've been meaning to update my portfolio and tonight seems like a good time.",
      "I should probably respond to some work emails that came in late today.",
      "I have this training module I've been putting off and should probably complete it.",
      "My desk at work is a mess - I should probably organize my files digitally tonight.",
      "I have some networking I should catch up on for work - been neglecting it lately.",
      "I should probably review tomorrow's schedule and make sure I'm prepared.",
      "I've been meaning to update my LinkedIn profile and should probably do that tonight.",
      "I have some work-related reading I've been putting off for weeks now.",
      "I should probably back up my work computer - haven't done it in a while.",
      "I have this online course for work that I should make progress on tonight.",
      "I should probably clean up my email inbox - it's getting pretty overwhelming.",
      "I have some invoices I should probably review and approve tonight.",
      "I should probably update my project status reports before tomorrow.",
      "I've been meaning to research some industry trends for work - good time to catch up.",
      "I should probably practice my presentation one more time before tomorrow.",
      "I have some work contacts I should probably touch base with tonight.",
      "I should probably review my quarterly goals and see how I'm tracking.",
      "I've been meaning to organize my digital workspace and tonight's a good opportunity."
    ]
  },
  family: {
    friendly: [
      "My mom just called and really needs help with something at home - I should probably go.",
      "My sister's having a tough day and asked if I could come over for a bit.",
      "My dad's trying to fix something and specifically asked for my help tonight.",
      "I promised my grandma I'd call her tonight and she gets worried if I'm late.",
      "My family is having a little get-together and I should probably make an appearance.",
      "My cousin just got back from traveling and the whole family is meeting up tonight.",
      "My mom made dinner and asked if I could join - it's been a while since we all ate together.",
      "My brother needs help moving some furniture and asked if I could swing by.",
      "I promised to help my aunt with her computer issues tonight - she's been struggling with it.",
      "My family has a tradition of Sunday dinners and I really shouldn't miss it again.",
      "My niece has a school play practice and I promised I'd help her run lines.",
      "My parents want to discuss some family plans and asked if I could come over tonight.",
      "My grandmother is teaching me her secret recipe and tonight was our scheduled cooking session.",
      "My family is planning a surprise party and I need to help with preparations.",
      "My mom found some old photos and wants to go through them together tonight.",
      "My dad started a new hobby and is excited to show me what he's been working on.",
      "My sister needs help with her job application and I promised to review it with her tonight.",
      "I committed to helping my uncle with his garage cleanup this evening.",
      "My family is having a game night and I already told them I'd bring snacks.",
      "My cousin is going through a breakup and really needs someone to talk to tonight.",
      "I promised to help my mom plan my dad's birthday surprise for next week.",
      "My grandpa wants to tell me stories about the old days and I love hearing them.",
      "My family is trying a new restaurant together and I already made the reservation.",
      "My nephew has been asking me to help him with his science project all week.",
      "I promised my parents I'd help them figure out their new smart TV tonight."
    ],
    urgent: [
      "Family emergency - my grandmother fell and I need to get to the hospital immediately!",
      "My mom just called crying - something happened with my dad and I have to go NOW!",
      "URGENT: My sister's car broke down in a dangerous area and I need to pick her up!",
      "My family dog is at the emergency vet and they need me there right away!",
      "My mom locked herself out and my dad's out of town - I have to go help her!",
      "My brother was in a minor accident - he's okay but I need to deal with insurance stuff now!",
      "My grandmother is having chest pains - I'm driving her to the emergency room!",
      "Family crisis: my parents are fighting badly and I need to go mediate before it gets worse!",
      "My nephew broke his arm and my sister needs me at the hospital immediately!",
      "URGENT: My mom's basement is flooding and I need to help move everything NOW!",
      "My dad had a panic attack - he's okay but I need to be there with him right now!",
      "My sister's babysitter bailed last minute and she has to work - I need to watch my niece!",
      "Emergency: my family's house alarm is going off and police want someone there immediately!",
      "My mom fell down the stairs - she seems okay but I need to take her for X-rays!",
      "My brother's wife went into labor early - I need to watch their other kids right now!",
      "Family emergency: my grandfather is confused and wandering - we need to find him!",
      "My parents' basement pipe burst and I need to help with the water damage immediately!",
      "Urgent: my sister's ex is harassing her and I need to be there for support right now!",
      "My family cat got out and we need all hands searching before it gets dark!",
      "Emergency at my parents' house - carbon monoxide detector going off and they need help!",
      "My mom accidentally overdosed on her medication - I'm taking her to get checked out!",
      "My brother's been drinking and threatening to drive - I need to get his keys immediately!",
      "Family crisis: my dad lost his job today and my mom needs me there for emotional support!",
      "Urgent: my grandmother had a fall and can't get up - I'm the closest family member!",
      "My sister's house was broken into - she's scared and needs me there while police investigate!"
    ],
    subtle: [
      "I should probably check in with my family tonight - haven't talked to them in a few days.",
      "My mom mentioned she might need help with something, so I should probably call her.",
      "I've been meaning to visit my grandmother and tonight might be a good time.",
      "I should probably touch base with my siblings - we usually catch up on Sundays.",
      "My family group chat has been active and I should probably see what's going on.",
      "I promised to help my dad with his computer sometime this week - might as well be tonight.",
      "My mom's been sending me recipes and I should probably try making one tonight.",
      "I should probably call my aunt back - she left a voicemail earlier today.",
      "My family always does a weekly check-in call and tonight's usually the night.",
      "I should probably help my brother with that project he mentioned last week.",
      "My grandmother likes her goodnight calls and I haven't talked to her in a couple days.",
      "I should probably sort through some old family photos that have been sitting in a box.",
      "My cousin asked for some advice and I've been meaning to call her back.",
      "I should probably video call my family since we haven't done that in a while.",
      "My mom mentioned wanting to plan a family get-together and I should help with that.",
      "I've been meaning to teach my dad how to use his new phone - good time to do it.",
      "I should probably check if my parents need anything from the store tomorrow.",
      "My family has been planning a vacation and I should probably contribute to the planning.",
      "I should probably help my sister practice for her job interview tomorrow.",
      "My family usually shares what we're grateful for on Sunday nights - it's become a tradition.",
      "I should probably organize some family photos on my computer tonight.",
      "My mom has been asking about my work and I should probably give her a proper update.",
      "I should probably help my uncle with his Facebook account - he's been struggling with it.",
      "My family likes to coordinate schedules for the week ahead on Sunday evenings.",
      "I should probably write thank you notes for the birthday gifts my family sent me."
    ]
  },
  health: {
    friendly: [
      "I'm starting to feel a bit under the weather and should probably rest up tonight.",
      "I have a doctor's appointment early tomorrow and they said to get plenty of sleep beforehand.",
      "I'm feeling a little dizzy and think I should probably take it easy this evening.",
      "I've had a headache coming on all day and should probably lie down for a bit.",
      "I think I might be getting what's going around - better to rest before it gets worse.",
      "My allergies are acting up really badly today and I should probably avoid going out tonight.",
      "I've been feeling pretty exhausted lately and my doctor said I need to prioritize sleep.",
      "I have some medication I need to take that makes me drowsy, so I should head home.",
      "I'm feeling a bit nauseous and think I should probably get some fresh air and rest.",
      "My back has been bothering me all week and I should probably do some stretches and rest.",
      "I have a therapy appointment tomorrow and usually like to prepare mentally the night before.",
      "I've been getting over a cold and don't want to risk spreading anything to others.",
      "My stomach's been a bit upset today and I think I should stick to bland food and rest.",
      "I have a blood test in the morning and need to fast, so I should probably head home soon.",
      "I've been dealing with some anxiety today and my usual coping routine involves quiet time at home.",
      "My physical therapist said I should ice my injury tonight and keep it elevated.",
      "I'm supposed to track my sleep patterns for my doctor and tonight's an important data point.",
      "I've been having trouble sleeping and want to try going to bed earlier tonight.",
      "My chiropractor recommended I do specific exercises tonight for my neck pain.",
      "I'm feeling pretty run down and think I'm fighting off something - better to rest up.",
      "I have to take my medication with food at a specific time tonight at home.",
      "My energy levels have been low lately and I'm trying to establish better evening routines.",
      "I've been having mild headaches and think screen time tonight might make it worse.",
      "My doctor said to monitor my symptoms and I should probably do that in a quiet environment.",
      "I'm trying to reduce stress and my therapist recommended having more quiet evenings at home."
    ],
    urgent: [
      "I'm having severe chest pains and need to get to the emergency room immediately!",
      "My migraine just hit like a truck - I can barely see and need to get home now!",
      "I think I'm having an allergic reaction - my throat is starting to close up!",
      "I'm experiencing severe stomach pains and think it might be appendicitis - going to ER!",
      "I just started having trouble breathing and need medical attention right away!",
      "My blood pressure medication is making me extremely dizzy - I need to lie down immediately!",
      "I think I'm having a panic attack - I can't breathe properly and need to get somewhere safe!",
      "I'm bleeding heavily from a cut and need to get stitches immediately!",
      "I'm having severe abdominal pain and vomiting - think it's food poisoning and need help!",
      "My back just went out completely - I can barely move and need someone to drive me home!",
      "I'm having an asthma attack and my inhaler isn't working - need to get to a hospital!",
      "I think I broke my wrist - it's swelling rapidly and the pain is unbearable!",
      "I'm having severe side effects from new medication - need to contact my doctor immediately!",
      "I'm experiencing signs of a concussion from earlier - getting dizzy and confused!",
      "My diabetes is acting up - my blood sugar dropped dangerously low and I feel terrible!",
      "I'm having a severe anxiety attack and can't stop shaking - need to get somewhere quiet!",
      "I think I have food poisoning - I've been throwing up for an hour and feel awful!",
      "My old injury just flared up badly - I'm in excruciating pain and can barely walk!",
      "I'm having heart palpitations and chest tightness - think I need to see a doctor now!",
      "I just twisted my ankle badly - it's already swelling and I can't put weight on it!",
      "I'm having a severe headache with vision problems - might be a migraine emergency!",
      "I think I'm having a reaction to something I ate - breaking out in hives everywhere!",
      "My chronic condition is flaring up badly - need to get home and take emergency medication!",
      "I just got a deep cut that won't stop bleeding - need medical attention immediately!",
      "I'm experiencing severe dizziness and nausea - might be an inner ear infection!"
    ],
    subtle: [
      "I'm feeling a bit tired tonight and should probably get to bed at a reasonable hour.",
      "I've been trying to establish better sleep habits and tonight seems like a good night to start.",
      "I should probably take my vitamins and do my evening skincare routine tonight.",
      "I've been feeling a little stressed lately and could use some quiet time to decompress.",
      "I should probably do some light stretching tonight - I've been sitting at a desk all day.",
      "I've been meaning to try that meditation app and tonight might be a good time.",
      "I should probably drink more water tonight - I don't think I've had enough today.",
      "I've been trying to cut back on late nights and should probably stick to that goal.",
      "I should probably take a hot bath tonight - it usually helps me relax.",
      "I've been wanting to try going to bed without looking at screens and tonight's a good test.",
      "I should probably do some journaling tonight - it helps me process the day.",
      "I've been meaning to practice some breathing exercises and have time tonight.",
      "I should probably organize my medication schedule for the week ahead.",
      "I've been trying to eat dinner earlier and should probably stick to that routine tonight.",
      "I should probably do some gentle yoga tonight - my body feels a bit stiff.",
      "I've been meaning to track my mood in my health app and should do that tonight.",
      "I should probably prep my healthy lunch for tomorrow while I have motivation.",
      "I've been trying to reduce caffeine and should probably have herbal tea tonight instead.",
      "I should probably check in with my fitness tracker goals and plan tomorrow's activities.",
      "I've been meaning to read that book on mindfulness and tonight's a good opportunity.",
      "I should probably do my physical therapy exercises - I've been putting them off.",
      "I've been trying to establish a consistent evening routine and should stick with it.",
      "I should probably take some time to plan healthy meals for this week.",
      "I've been meaning to research some stress-reduction techniques and have time tonight.",
      "I should probably set up my workspace ergonomically - my neck has been bothering me."
    ]
  },
  transport: {
    friendly: [
      "My car is acting up and I should probably get it looked at before driving anywhere tonight.",
      "I missed the last convenient bus and the next one doesn't come for an hour.",
      "My usual ride canceled on me and I haven't been able to find another one yet.",
      "The subway is delayed due to track maintenance and I'm not sure when it'll be running.",
      "My car is in the shop and my backup transportation plan fell through.",
      "There's unexpected construction on my usual route and it's adding hours to the drive.",
      "My ride-share app is showing surge pricing that's way beyond my budget right now.",
      "I lent my car to a family member and they haven't brought it back yet.",
      "My bike has a flat tire and the repair shop is closed until tomorrow.",
      "The weather turned bad and I don't feel comfortable driving in these conditions.",
      "My car battery died and I'm waiting for roadside assistance to come help.",
      "The bridge I need to cross is closed for emergency repairs.",
      "My regular carpool buddy had to cancel and I haven't found an alternative yet.",
      "There's a major accident on the highway and traffic is completely stopped.",
      "My car failed inspection and I can't legally drive it until I get it fixed.",
      "The parking situation where we're going is impossible and I don't want to stress about it.",
      "My GPS is acting up and I'm not confident about navigating there in the dark.",
      "I just realized my car registration expired and I should probably deal with that first.",
      "My usual route has road closures and I'm not familiar with the alternate paths.",
      "I'm having car trouble and don't want to risk breaking down halfway there.",
      "The train I usually take is canceled due to crew shortages.",
      "My friend was going to give me a ride but they just got called into work.",
      "There's a street fair blocking off my entire neighborhood and I can't get my car out.",
      "My car insurance lapsed and I need to sort that out before driving anywhere.",
      "I'm low on gas and the stations on my route are all closed for the night."
    ],
    urgent: [
      "My car just broke down and I'm stranded - need to deal with this emergency immediately!",
      "URGENT: I'm stuck in traffic due to a major accident and there's no way I'm getting there tonight!",
      "My ride just canceled LAST MINUTE and there's no public transport running this late!",
      "EMERGENCY: My car battery died in a bad neighborhood and I need to get help immediately!",
      "Major highway closure due to chemical spill - I'm stuck and can't get there for hours!",
      "My car just started making horrible noises and I need to pull over immediately for safety!",
      "URGENT: My driver's license expired today and I just realized I can't legally drive!",
      "My car tire just blew out on the freeway - I'm waiting for emergency roadside assistance!",
      "Major train derailment has shut down all rail service - I have no way to get there!",
      "My car engine is overheating and smoking - I had to stop and can't continue driving!",
      "EMERGENCY: Bridge collapse has closed the only route - I'm stuck on this side of the city!",
      "My ride-share driver was in an accident - I'm stranded and there are no other cars available!",
      "URGENT: My car was just towed and I need to deal with getting it back immediately!",
      "Major snowstorm hit and roads are completely impassable - authorities say don't drive!",
      "My car was hit in the parking lot - I'm dealing with police and insurance right now!",
      "EMERGENCY: I'm out of gas on a closed road with no service stations for miles!",
      "Major flooding has made all roads in my area impassable - I literally can't leave!",
      "My car's brakes are failing - I barely made it home and can't drive anywhere!",
      "URGENT: My motorcycle won't start and it's my only transportation - stuck at home!",
      "Major sinkhole opened up on the main road - the entire area is evacuated!",
      "My car keys are locked inside my car and I'm stranded in a parking lot!",
      "EMERGENCY: Multi-car pileup has shut down the interstate indefinitely!",
      "My car is leaking fuel - it's not safe to drive and I need immediate help!",
      "URGENT: My ride was arrested at a traffic stop and I'm stranded at the scene!",
      "Major power outage has disabled all traffic lights and they're telling people not to drive!"
    ],
    subtle: [
      "I should probably check my car's oil before driving anywhere tonight - it's been a while.",
      "The parking situation downtown is pretty complicated and I'd rather not deal with it tonight.",
      "I'm trying to save on gas money this week and should probably limit unnecessary trips.",
      "I should probably give my car a quick maintenance check since I've been putting it off.",
      "The traffic around that area gets pretty heavy in the evenings - might want to avoid it.",
      "I'm not super familiar with that part of town and would rather navigate it during daylight.",
      "I should probably check if there are any planned road closures before heading out.",
      "My car's been making a small noise and I should probably listen to it more carefully tonight.",
      "I've been trying to walk more instead of driving and tonight seems like a good night to stick with that.",
      "I should probably clean my windshield and check my headlights before any evening driving.",
      "The weather forecast mentioned possible rain and I don't love driving in that.",
      "I should probably check my car's tire pressure - it's been on my to-do list for a while.",
      "I'm trying to be more environmentally conscious and reduce my driving when possible.",
      "I should probably update my car insurance information before I forget again.",
      "My car needs an inspection soon and I should probably check what needs to be done.",
      "I've been meaning to clean out my car and tonight might be a good time to do that.",
      "I should probably check if my car registration needs to be renewed soon.",
      "The route there involves a lot of highway driving and I'm more comfortable with local roads.",
      "I should probably make sure I have emergency supplies in my car before any trips.",
      "I've been trying to plan my errands better to reduce back-and-forth driving.",
      "I should probably check the traffic patterns for that area before committing to drive there.",
      "My car's been due for a wash and I should probably take care of that maintenance.",
      "I've been meaning to organize my car's emergency kit and tonight's a good time.",
      "I should probably check if there are any construction projects affecting my usual routes.",
      "I'm trying to be more mindful about when I choose to drive versus other transportation options."
    ]
  }
};

export function getRandomFallbackExcuse(category: string, tone: string): string {
  const categoryExcuses = fallbackExcuses[category as keyof typeof fallbackExcuses];
  if (!categoryExcuses) return "I need to step away for a bit.";
  
  const toneExcuses = categoryExcuses[tone as keyof typeof categoryExcuses];
  if (!toneExcuses || toneExcuses.length === 0) return "I need to step away for a bit.";
  
  const randomIndex = Math.floor(Math.random() * toneExcuses.length);
  return toneExcuses[randomIndex];
}